ZSH=$HOME/.oh-my-zsh

ZSH_THEME="charlie"

DISABLE_AUTO_TITLE="true"

plugins=(git bundler gem heroku rails3 rvm tmux)

#Oh-My-Zsh
source $ZSH/oh-my-zsh.sh

#RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

#Tmuxifier
[[ -s "$HOME/.tmuxifier/init.sh" ]] && source "$HOME/.tmuxifier/init.sh"

#Path
export PATH=$PATH:$HOME/.custom_scripts:$HOME/bin:$HOME/scripts

#History
bindkey '\e[A' history-beginning-search-backward
bindkey '\e[B' history-beginning-search-forward
