ZSH=$HOME/.oh-my-zsh

ZSH_THEME="charlie"

DISABLE_AUTO_TITLE="true"

plugins=(git bundler gem heroku rails3 rvm tmux)

#Oh-My-Zsh
source $ZSH/oh-my-zsh.sh

#RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

#Tmuxifier
[[ -s "$HOME/.tmuxifier/init.sh" ]] && source "$HOME/.tmuxifier/init.sh"

#History
bindkey '\e[A' history-beginning-search-backward
bindkey '\e[B' history-beginning-search-forward

#ENV
export EDITOR=vim
export PAGER=less
export PATH=$PATH:$HOME/.custom_scripts:$HOME/bin:$HOME/scripts
export PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

# Broadcast
if [ $SSH_CONNECTION ]; then; echo "Bow before me, for I am root." | wall; fi
